// Unity build file for the Oak scripting language library.
// Compiles all Oak C sources as a single translation unit within Unreal's build system.

#include "common/oak_allocator.c"
#include "common/oak_arena.c"
#include "common/oak_dynarr.c"
#include "common/oak_file_map.c"
#include "common/oak_htable.c"
#include "common/oak_log.c"
#include "common/oak_module_loader.c"
#include "common/oak_module_loader_compile.c"
#include "common/oak_module_loader_native.c"
#include "common/oak_module_loader_path.c"
#include "common/oak_run.c"
#include "compiler/oak_compiler.c"
#include "compiler/oak_compiler_attrs.c"
#include "compiler/oak_compiler_builtins.c"
#include "compiler/oak_compiler_call_arg.c"
#include "compiler/oak_compiler_call_method.c"
#include "compiler/oak_compiler_calls.c"
#include "compiler/oak_compiler_diagnostics.c"
#include "compiler/oak_compiler_emit.c"
#include "compiler/oak_compiler_enums.c"
#include "compiler/oak_compiler_expr.c"
#include "compiler/oak_compiler_expr_assign.c"
#include "compiler/oak_compiler_expr_binary.c"
#include "compiler/oak_compiler_expr_collection.c"
#include "compiler/oak_compiler_expr_fn.c"
#include "compiler/oak_compiler_expr_member.c"
#include "compiler/oak_compiler_expr_record.c"
#include "compiler/oak_compiler_fn_argcheck.c"
#include "compiler/oak_compiler_fn_body.c"
#include "compiler/oak_compiler_fn_decl.c"
#include "compiler/oak_compiler_fn_register.c"
#include "compiler/oak_compiler_imports.c"
#include "compiler/oak_compiler_lifecycle.c"
#include "compiler/oak_compiler_method_builtins.c"
#include "compiler/oak_compiler_method_table.c"
#include "compiler/oak_compiler_modules.c"
#include "compiler/oak_compiler_pipeline.c"
#include "compiler/oak_compiler_record_registry.c"
#include "compiler/oak_compiler_records.c"
#include "compiler/oak_compiler_records_native.c"
#include "compiler/oak_compiler_scope.c"
#include "compiler/oak_compiler_stmt.c"
#include "compiler/oak_compiler_stmt_for.c"
#include "compiler/oak_compiler_symbols.c"
#include "compiler/oak_compiler_traits.c"
#include "compiler/oak_compiler_type_infer.c"
#include "compiler/oak_compiler_type_infer_call.c"
#include "compiler/oak_compiler_types.c"
#include "lexer/oak_lexer.c"
#include "lexer/oak_lexer_buffer.c"
#include "lexer/oak_token.c"
#include "parser/oak_parser.c"
#include "parser/oak_parser_ast.c"
#include "parser/oak_parser_grammar.c"
#include "parser/oak_parser_pratt.c"
#include "parser/oak_parser_rules.c"
#include "runtime/oak_bind.c"
#include "runtime/oak_chunk.c"
#include "runtime/oak_cycle.c"
#include "runtime/oak_module.c"
#include "runtime/oak_symbol.c"
#include "runtime/oak_type.c"
#include "runtime/oak_value.c"
// oak_value_json.c excluded; Unreal builds Oak without the yyjson dependency.
#include "runtime/oak_value_repr.c"

struct oak_obj_string_t* oak_value_to_string(struct oak_allocator_t* allocator,
                                             struct oak_value_t value)
{
  return oak_string_from_value_repr(allocator, value);
}
#include "stdlib/oak_stdlib.c"
#include "stdlib/oak_stdlib_file.c"
#include "stdlib/oak_stdlib_math.c"
#include "vm/oak_vm.c"
#include "vm/oak_vm_arith.c"
#include "vm/oak_vm_call.c"
#include "vm/oak_vm_control.c"
#include "vm/oak_vm_error.c"
#include "vm/oak_vm_object.c"
#include "vm/oak_vm_stack.c"
